#!/bin/bash

# wordarenad - Startup script for wordarenad

. /etc/rc.d/init.d/functions

SERVICE_NAME=wordarenad
PATH_TO_JAR=/opt/wordarena/wordarenad.jar
PID_FILE=/var/run/wordarena/wordarenad.pid
LOG_FILE=/var/log/wordarena/wordarenad.log

WORDARENA_USER=wordarena
WORDARENA_GROUP=wordarena

# Starts the server
start()
{
    echo "Starting $SERVICE_NAME ..."

    # Make sure the default pidfile and log directories exist
    PIDDIR=`dirname $PID_FILE`
    if [ ! -d $PIDDIR ]; then
        install -d -m 0755 -o $WORDARENA_USER -g $WORDARENA_GROUP $PIDDIR
    fi
    LOGDIR=`dirname $LOG_FILE`
    if [ ! -d $LOGDIR ]; then
        install -d -m 0755 -o $WORDARENA_USER -g $WORDARENA_GROUP $LOGDIR
    fi

    if [ ! -f $PID_FILE ]; then
        # Cette syntaxe est bien mais on n'a pas le PID
        #daemon --user "$WORDARENA_USER" "nohup java -jar $PATH_TO_JAR 2>&1 >> $LOG_FILE &"
        # Cette syntaxe lance le programme en tant que root et pas user wordarena
        nohup java -jar $PATH_TO_JAR 2>&1 >> $LOG_FILE &
        echo $! > $PID_FILE
        echo "$SERVICE_NAME started ..."
    else
        echo "$SERVICE_NAME is already running ..."
    fi
}

# Stops the server
stop()
{
    if [ -f $PID_FILE ]; then
        PID=$(cat $PID_FILE);
            
        echo "$SERVICE_NAME stoping ..."
        kill $PID;
            
        echo "$SERVICE_NAME stopped ..."
        rm $PID_FILE
    else
        echo "$SERVICE_NAME is not running ..."
    fi
}

# Restarts the server
restart () {
	stop
	start
}

RETVAL=0

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status -p $PID_FILE
    RETVAL=$?
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
    RETVAL=1
esac
